### PR TITLE
Decorations and window moving

### PR DESCRIPTION
**Pull request by harmjan**
Currently the windows have a border and the focus can be changed using keyboard shortcuts in this PR.
I'll try to also fix the window moving which seems to have problems.

### CODE REVIEW

**Comment by harmjan** [comment]
I add focus handling and global key grabs, I fixed the key grabs (even with numlock/capslock/scrollock). Window moving is still beyond wonky and needs some work.

**Comment by harmjan** [comment]
I think this is ready to be merged. The window moving is now VIM style which is not ideal but at least works decently bug free. The tests now fail but I don't agree with some of the tests, I don't agree that the translateModifiers should return zero on an unknown modifier. Let me know what you think @nspruit and @MartinRogalla.

**Comment by MartinRogalla** [comment]
Regarding the test I agree that it should be changed. Going through the rest of the pull-request right now.

**Comment by MartinRogalla** [comment]
I get the following result when I try to run it. Normally I can run xterm's fine, don't know what's going on here.
screenshot from 2015-01-25 20 29 14

**Comment by harmjan** [comment]
Weird, for me it looks like:
airwm
Those are colors used by the borders though, maybe something isn't really portable.

**Comment by MartinRogalla** [comment]
@nspruit  Could you try and run this? Is this working fine for you?

**Comment by nspruit** [comment]
I'll check whether it's working for me tomorrow

**Comment by nspruit** [comment]
Doesn't work for me either. When I just launch make, the resulting screen is the same as the one @MartinRogalla had

**Comment by MartinRogalla** [comment]
@harmjan do you have any unpushed changes?

**Comment by harmjan** [comment]
Nope, I just reverted everything and it still works for me.

I just remembered you have to do npm install again because the dependency changed, you need the new version of node-x11.

**Comment by nspruit** [comment]
After running npm install again, it works indeed. If it also works for @MartinRogalla this PR can be merged in my opinion.

**Comment by MartinRogalla** [comment]
Yes that was indeed the culprit.

**Pull request merged**
